# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

partial_dist_Cpp <- function(embeddings, k1, k2, npcs, stride) {
    .Call('_moduli_partial_dist_Cpp', PACKAGE = 'moduli', embeddings, k1, k2, npcs, stride)
}

