# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

partial_moduli_dist <- function(embeddings, emb_metric, moduli_metric, k1, k2, npcs, stride) {
    .Call('_moduli_partial_moduli_dist', PACKAGE = 'moduli', embeddings, emb_metric, moduli_metric, k1, k2, npcs, stride)
}

