# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_Cpp <- function(embeddings, idx, npcs, pow) {
    .Call('_moduli_dist_Cpp', PACKAGE = 'moduli', embeddings, idx, npcs, pow)
}

